call pathogen#incubate()
"call pathogen#runtime_append_all_bundles()
call pathogen#helptags()
syntax on
filetype indent plugin on
"set tw=80
set wm=2
set tabstop=4 
set softtabstop=4
set expandtab
set shiftwidth=4 
set shiftround
set autoindent
set hlsearch
set incsearch
set ruler
"set number
set background=dark
set modeline
set tabstop=8 
set expandtab 
set shiftwidth=4 
set softtabstop=4

