# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi
if [ -f ~/Projects/dotfiles/bash/colors ] ; then
    . ~/Projects/dotfiles/bash/colors 
fi

if [ ! -d ${HOME}/Projects/dotfiles ] ; then
    printf "${Red}%-17s${Color_Off}\n" "-----NOTICE!-----"
    printf "You do not have your dotfiles checked out from github.\n"
    printf "Consider doing that.\n"
fi
if [ -f /etc/bash_completion.d/git ] ; then
    . /etc/bash_completion.d/git
fi
if [ -f /etc/bash_completion ] ; then
    . /etc/bash_completion 
fi
if [ -f ${HOME}/Projects/dotfiles/bash/functions ] ; then
    . ${HOME}/Projects/dotfiles/bash/functions
fi 

export GIT_PS1_SHOWDIRTYSTATE=true
export GIT_PS1_SHOWUNTRACKEDFILES=true

if [ ${HOSTNAME} == "blob" ] ; then
    export http_proxy=http://www-proxy.ericsson.se:8080
fi
if [ ${HOSTNAME} == "double" ] ; then
    export http_proxy=http://www-proxy.ericsson.se:8080
fi


force_color_prompt=yes
if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt="yes"
        export TERM="screen-256color"
    else
	color_prompt=
    fi
fi
unset PS1
unset PROMPT_COMMAND
. ~/bin/git-prompt.sh
if [ ${color_prompt} = "yes" ] ; then
    export PS1="${BIPurple}[ -- \w -- ]${Color_Off} | ${BIRed}[ git: \$(__git_ps1) ]${Color_Off}\n[${Green}\u@\h]\$>"
else
    export PS1="[\u@\h]"
fi
unset color_prompt
if [ -x /usr/bin/dircolors ] ; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
if [ -e ${HOME}/java ] ; then
    export JAVA_HOME=${HOME}/java
    export PATH=${JAVA_HOME}/bin:${PATH}:${HOME}/bin
else
    export PATH=${PATH}:${HOME}/bin
fi
export HISTTIMEFORMAT="%F %T "
export HISTCONTROL=ignoreboth
export HISTSIZE=2000
unset SSH_ASKPASS
export WORKON_HOME="${HOME}/PythonEnvs"
. /usr/bin/virtualenvwrapper.sh
